<?php

namespace App\Fleet;

use GuzzleHttp\Psr7\Utils;
use Illuminate\Http\Client\ConnectionException;
use Illuminate\Support\Facades\Http;
use Psr\Http\Message\StreamInterface;
use RuntimeException;

/**
 * Talks to one host's cic-agent.
 *
 * Every method returns what it OBSERVED, and says so. The agent follows the
 * same rule on its side: its `ok` is the verdict, not the transport, and a
 * delete that removed three of four parts reports `partially_removed` with the
 * breakdown rather than success. This class must not flatten that back into a
 * boolean - a site whose container is gone but whose vhost still answers is
 * not "deleted", and reporting it as such is how a domain keeps serving a
 * customer who has left.
 */
class AgentClient
{
    public function __construct(
        public readonly string $host,
        private readonly string $baseUrl,
        private readonly string $token,
        private readonly int $timeout = 120,
    ) {}

    public static function for(string $host): self
    {
        $cfg = config("fleet.hosts.$host");
        if (! $cfg) {
            throw new RuntimeException("Unknown host [$host]. Known hosts: ".implode(', ', array_keys(config('fleet.hosts'))));
        }

        // A host we have explicitly ruled out must fail here, not merely be
        // absent from a list someone could edit.
        if (in_array($cfg['ip'], config('fleet.forbidden_ips'), true)) {
            throw new RuntimeException("Host [$host] resolves to {$cfg['ip']}, which is out of scope for this fleet.");
        }

        // config(), never env(): see config/fleet.php. An env() call here
        // returns null under a cached config, so the agent would be called
        // with an empty bearer token in production and refuse every request.
        $token = config("fleet.tokens.$host");
        if (! $token) {
            throw new RuntimeException(
                "No agent token for [$host]. Set CIC_TOKEN_".strtoupper($host).' in .env; '.
                'it is generated by infra/install-agent.sh and lives in /opt/codeinchrome/etc/agent.env on the host.'
            );
        }

        return new self($host, "http://127.0.0.1:{$cfg['tunnel_port']}", $token, config('fleet.timeout'));
    }

    public function health(): array
    {
        return $this->send('get', '/healthz', authenticated: false);
    }

    /** @return array<int, array{id: string, current: bool, image: string}> */
    public function imageStatuses(): array
    {
        return $this->send('get', '/v1/images')['sites'] ?? [];
    }

    /** "recreated" or "current"; throws if the new container does not answer. */
    public function recreate(string $id): string
    {
        return $this->send('post', "/v1/sites/$id/recreate")['outcome'] ?? '';
    }

    public function hostStats(): array
    {
        return $this->send('get', '/v1/host/stats')['stats'] ?? [];
    }

    public function hostInfo(): array
    {
        return $this->send('get', '/v1/host');
    }

    /** @return array<int, array<string, mixed>> */
    public function sites(): array
    {
        return $this->send('get', '/v1/sites')['sites'] ?? [];
    }

    public function site(string $id): array
    {
        return $this->send('get', "/v1/sites/$id")['site'] ?? [];
    }

    public function createSite(string $id, string $domain, string $cpu, string $memory, int $diskGb = 1, int $cpuWeight = 1024): array
    {
        return $this->send('post', '/v1/sites', [
            'id' => $id, 'domain' => $domain, 'cpuLimit' => $cpu, 'cpuWeight' => $cpuWeight, 'memLimit' => $memory, 'diskGb' => $diskGb,
        ])['site'] ?? [];
    }

    /**
     * Apply new ceilings to a running site. Returns what the host says it
     * applied, per part: CPU and memory change immediately, and a disk only
     * ever grows - a smaller plan leaves it as it is.
     *
     * @return array<string, string>
     */
    public function setLimits(string $id, string $cpu, string $memory, int $diskGb, int $cpuWeight = 1024): array
    {
        return $this->send('put', "/v1/sites/$id/limits", [
            'cpuLimit' => $cpu, 'cpuWeight' => $cpuWeight, 'memLimit' => $memory, 'diskGb' => $diskGb,
        ])['applied'] ?? [];
    }

    /**
     * Run one allow-listed artisan or composer command. A non-zero exit is
     * returned as a result with ok=false, NOT thrown: the output is what the
     * caller needs to see.
     */
    /** $live names the run, so commandLive() can read its output while it runs. */
    public function runCommand(string $id, string $tool, array $args, bool $confirm = false, ?string $live = null): array
    {
        return $this->sendRaw('post', "/v1/sites/$id/command", ['tool' => $tool, 'args' => array_values($args), 'confirm' => $confirm]
            + ($live !== null ? ['live' => $live] : []));
    }

    /**
     * What the site's running command has printed from byte $from on, while it
     * runs (the editor shows it line by line).
     *
     * @return array{running: bool, output: string, next: int}
     */
    public function commandLive(string $id, string $key, int $from): array
    {
        return $this->send('get', "/v1/sites/$id/command/live", query: ['key' => $key, 'from' => $from])['live'] ?? ['running' => false, 'output' => '', 'next' => $from];
    }

    /**
     * The site's GitHub link (agent github.go): null when there is none.
     *
     * @return array{repo: string, branch: string, publicKey: string, state: string, hint?: string, lastPushAt?: string, lastCommit?: string}|null
     */
    public function github(string $id): ?array
    {
        $r = $this->send('get', "/v1/sites/$id/github");

        return ($r['linked'] ?? false) ? $r['github'] : null;
    }

    /** Link owner/repo (and push at once: "waiting_for_key" until the key is on GitHub). */
    public function linkGitHub(string $id, string $repo, string $branch): array
    {
        return $this->send('post', "/v1/sites/$id/github", ['repo' => $repo, 'branch' => $branch])['github'];
    }

    public function pushGitHub(string $id): array
    {
        return $this->send('post', "/v1/sites/$id/github/push")['github'];
    }

    /** Stop pushing; the site's deploy key is destroyed. */
    public function unlinkGitHub(string $id): void
    {
        $this->send('delete', "/v1/sites/$id/github");
    }

    /** @param  array{since?: int, file?: string}  $mark  only what the app log gained after this */
    public function logs(string $id, string $source, int $lines = 200, array $mark = []): array
    {
        return $this->send('get', "/v1/sites/$id/logs", query: ['source' => $source, 'lines' => $lines] + $mark)['log'] ?? [];
    }

    /** Replace the site's verified custom domains; the agent rewrites the vhost. */
    public function setAliases(string $id, array $aliases): array
    {
        return $this->send('put', "/v1/sites/$id/aliases", ['aliases' => array_values($aliases)])['site'] ?? [];
    }

    /** @return array<int, array<string, mixed>> one entry per site on the host */
    public function usage(): array
    {
        return $this->send('get', '/v1/usage')['usage'] ?? [];
    }

    /**
     * @return array<string, string> per part: "removed", "absent" or "failed".
     *
     * Three states rather than a boolean, because `docker rm -f` exits 0 for a
     * container that never existed - so a delete aimed at the wrong host used
     * to report success for work it had not done.
     */
    public function deleteSite(string $id): array
    {
        return $this->send('delete', "/v1/sites/$id")['parts'] ?? [];
    }

    /** @return array{path: string, entries: array, truncated: bool} */
    public function listFiles(string $id, string $path = '/'): array
    {
        return $this->send('get', "/v1/sites/$id/files", query: ['path' => $path])['listing'] ?? [];
    }

    public function readFile(string $id, string $path): string
    {
        return $this->readFileWithRevision($id, $path)['content'];
    }

    /** @return array{content: string, revision: string} */
    public function readFileWithRevision(string $id, string $path): array
    {
        $r = $this->send('get', "/v1/sites/$id/files", query: ['read' => 1, 'path' => $path]);

        return ['content' => $r['content'] ?? '', 'revision' => $r['revision'] ?? ''];
    }

    /**
     * @param  string  $expect  "" to write unconditionally, "absent" to create
     *                          only if missing, or the revision from a read.
     *                          A mismatch is an AgentRefused whose
     *                          detail['error'] is "conflict", and NOTHING was
     *                          written.
     */
    public function writeFile(string $id, string $path, string $content, string $expect = ''): array
    {
        return $this->send('put', "/v1/sites/$id/files", ['path' => $path, 'content' => $content, 'expect' => $expect]);
    }

    /**
     * Many files, checked together and written together as one version.
     *
     * @param  list<array{path: string, content: string, expect?: string}>  $files
     */
    public function writeMany(string $id, array $files, string $message = ''): array
    {
        return $this->send('put', "/v1/sites/$id/files/batch", ['files' => $files, 'message' => $message]);
    }

    /** Find-and-replace edits applied to one file as one version. */
    public function editFile(string $id, string $path, array $edits, string $expect = ''): array
    {
        return $this->send('post', "/v1/sites/$id/files/edit", ['path' => $path, 'edits' => $edits, 'expect' => $expect]);
    }

    /** PHP run inside the site's booted application: {output, exitCode, truncated, timedOut, elapsedMs}. */
    public function evalPhp(string $id, string $code): array
    {
        return $this->send('post', "/v1/sites/$id/eval", ['code' => $code])['result'] ?? [];
    }

    /** A session cookie for one of the site's OWN users, from the site's own session store: {name, value}. */
    public function loginCookie(string $id, int $userId, string $guard = 'web'): array
    {
        $r = $this->send('post', "/v1/sites/$id/login-cookie", ['userId' => $userId, 'guard' => $guard]);

        return ['name' => $r['name'] ?? '', 'value' => $r['value'] ?? ''];
    }

    /** A request to the site itself, made on its host: {status, headers, body, truncated, ms}. */
    public function siteRequest(string $id, array $request): array
    {
        return $this->send('post', "/v1/sites/$id/request", $request)['response'] ?? [];
    }

    public function deleteFile(string $id, string $path): bool
    {
        return (bool) ($this->send('delete', "/v1/sites/$id/files", query: ['path' => $path])['deleted'] ?? false);
    }

    /** Versions of a file, newest first; an empty path lists every change. */
    public function history(string $id, string $path = '', int $limit = 100): array
    {
        return $this->send('get', "/v1/sites/$id/history", query: ['path' => $path, 'limit' => $limit])['versions'] ?? [];
    }

    /** A file's contents at one version (a full 40-character commit id). */
    public function fileAt(string $id, string $rev, string $path): string
    {
        return (string) ($this->send('get', "/v1/sites/$id/history", query: ['rev' => $rev, 'path' => $path])['content'] ?? '');
    }

    /** Deleted files not since re-created, with the version to restore from. */
    public function bin(string $id, int $limit = 100): array
    {
        return $this->send('get', "/v1/sites/$id/bin", query: ['limit' => $limit])['bin'] ?? [];
    }

    /** Put a file back as it was at $rev; the restore is itself a new version. */
    public function restore(string $id, string $rev, string $path): array
    {
        return $this->send('post', "/v1/sites/$id/history/restore", ['rev' => $rev, 'path' => $path]);
    }

    /** Apply the site's PHP settings (0 = the image's default). Replaces the container. */
    public function setPhp(string $id, int $memoryMB, int $maxExecutionSeconds, int $uploadMB): array
    {
        return $this->send('put', "/v1/sites/$id/php", [
            'memoryMB' => $memoryMB, 'maxExecutionSeconds' => $maxExecutionSeconds, 'uploadMB' => $uploadMB,
        ])['applied'] ?? [];
    }

    /** Pause (container stopped, a 503 page served) or resume a site. */
    public function setSuspended(string $id, bool $suspended): array
    {
        return $this->send('put', "/v1/sites/$id/suspended", ['suspended' => $suspended])['applied'] ?? [];
    }

    /** Switch the site's queue worker, scheduler and Reverb. Replaces the container. */
    public function setBackground(string $id, bool $queue, bool $scheduler, bool $reverb): array
    {
        return $this->send('put', "/v1/sites/$id/background", ['queue' => $queue, 'scheduler' => $scheduler, 'reverb' => $reverb])['applied'] ?? [];
    }

    // ── Laravel Boost MCP ──

    /** One MCP request (tools/list or tools/call); params and result are raw JSON. */
    public function mcp(string $id, string $method, string $paramsJson): string
    {
        try {
            $response = Http::timeout(75)->acceptJson()->withToken($this->token)
                ->withBody('{"method":'.json_encode($method, JSON_UNESCAPED_SLASHES).',"params":'.$paramsJson.'}', 'application/json')
                ->post($this->baseUrl."/v1/sites/$id/mcp");
        } catch (ConnectionException $e) {
            throw new AgentUnreachable("Cannot reach the agent on [{$this->host}].", previous: $e);
        }
        $json = json_decode($response->body());
        if (! is_object($json) || ($json->ok ?? false) !== true) {
            throw new AgentRefused(sprintf('Agent on [%s] refused the MCP call: %s', $this->host, $json->error ?? 'unknown_error'),
                detail: ['error' => $json->error ?? 'unknown_error', 'hint' => $json->hint ?? 'no hint given']);
        }

        return json_encode($json->result ?? null, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
    }

    // ── the editor's language server ──

    /**
     * Sends JSON-RPC messages (already-encoded JSON, passed through untouched)
     * to the site's language server for one editor session; returns the raw
     * JSON of what came back.
     */
    public function lsp(string $id, string $session, string $messagesJson, int $waitMs): string
    {
        try {
            $response = Http::timeout(25)->acceptJson()->withToken($this->token)
                ->withBody('{"messages":'.$messagesJson.',"waitMs":'.$waitMs.'}', 'application/json')
                ->post($this->baseUrl."/v1/sites/$id/lsp/$session");
        } catch (ConnectionException $e) {
            throw new AgentUnreachable("Cannot reach the agent on [{$this->host}].", previous: $e);
        }
        $json = json_decode($response->body());
        if (! is_object($json) || ($json->ok ?? false) !== true) {
            throw new AgentRefused(sprintf('Agent on [%s] refused the language server exchange: %s', $this->host, $json->error ?? 'unknown_error'),
                detail: ['error' => $json->error ?? 'unknown_error', 'hint' => $json->hint ?? 'no hint given']);
        }

        return json_encode($json->messages ?? [], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
    }

    public function lspClose(string $id, string $session): void
    {
        $this->send('delete', "/v1/sites/$id/lsp/$session");
    }

    // ── backups ──

    /** @return array{backups: array, operation: ?array} newest first; operation is the current or last backup/restore */
    public function backups(string $id): array
    {
        $r = $this->send('get', "/v1/sites/$id/backups");

        return ['backups' => $r['backups'] ?? [], 'operation' => $r['operation'] ?? null];
    }

    /** Starts a backup now, in the background. */
    public function backupNow(string $id): array
    {
        return $this->send('post', "/v1/sites/$id/backups")['operation'] ?? [];
    }

    /** Backs the site up as it is, then restores $snapshot (files and database), in the background. */
    public function restoreBackup(string $id, string $snapshot): array
    {
        return $this->send('post', "/v1/sites/$id/backups/restore", ['snapshot' => $snapshot, 'confirm' => true])['operation'] ?? [];
    }

    // ── the file manager ──

    public function mkdir(string $id, string $path): array
    {
        return $this->send('post', "/v1/sites/$id/files/mkdir", ['path' => $path]);
    }

    public function move(string $id, string $from, string $to): array
    {
        return $this->send('post', "/v1/sites/$id/files/move", ['from' => $from, 'to' => $to]);
    }

    public function copy(string $id, string $from, string $to): array
    {
        return $this->send('post', "/v1/sites/$id/files/copy", ['from' => $from, 'to' => $to]);
    }

    public function zip(string $id, string $from, string $to): array
    {
        return $this->send('post', "/v1/sites/$id/files/zip", ['from' => $from, 'to' => $to]);
    }

    public function unzip(string $id, string $archive, string $into): array
    {
        return $this->send('post', "/v1/sites/$id/files/unzip", ['archive' => $archive, 'into' => $into]);
    }

    /** A folder and everything in it; refused (needs_confirm) without $confirm. */
    public function deleteTree(string $id, string $path, bool $confirm): array
    {
        return $this->send('delete', "/v1/sites/$id/tree", query: ['path' => $path, 'confirm' => $confirm ? 1 : 0]);
    }

    /** rmdir: the host removes the folder only if it is empty at that moment. */
    public function deleteEmptyDir(string $id, string $path): array
    {
        return $this->send('delete', "/v1/sites/$id/tree", query: ['path' => $path, 'empty' => 1]);
    }

    /** Every file path in the site for Quick Open: ['paths' => [...], 'truncated' => bool]. */
    public function paths(string $id): array
    {
        $r = $this->send('get', "/v1/sites/$id/paths");

        return ['paths' => $r['paths'] ?? [], 'truncated' => (bool) ($r['truncated'] ?? false)];
    }

    /** How widely each site on this host reaches out (agent sites/egress.go): {sites: [...]}. */
    public function egress(): array
    {
        return $this->send('get', '/v1/egress');
    }

    /** When a person last loaded each site on this host (agent sites/visits.go): {sites: [{site, last}]}. */
    /** $ignore: the fleet's own addresses (its page renderer is not a visitor). */
    public function visits(array $ignore = []): array
    {
        return $this->send('get', '/v1/visits'.($ignore ? '?'.implode('&', array_map(fn ($ip) => 'ignore='.rawurlencode($ip), $ignore)) : ''));
    }

    /** Which names each site looked up since $since: ['site' => ['name' => count]] (agent dnsreport.go). */
    public function dnsLookups(int $since): array
    {
        return $this->send('get', "/v1/dns?since=$since")['sites'] ?? [];
    }

    /** A hosted page's DOM after its scripts ran (agent render.go): ['dom' => ..., 'ms' => ...]. */
    /**
     * A platform page at phone, tablet and desktop size, as PNGs (base64).
     *
     * @return list<array{name: string, width: int, height: int, png: string}>
     */
    /** @param  string|list<string>  $url  one address, or one per screen size (sign-in links are used once) */
    public function renderShots(string|array $url): array
    {
        try {
            $response = Http::timeout(170)->acceptJson()->withToken($this->token)->post($this->baseUrl.'/v1/render/shots',
                is_array($url) ? ['urls' => array_values($url)] : ['url' => $url]);
        } catch (ConnectionException $e) {
            throw new AgentUnreachable("Cannot reach the agent on [{$this->host}] to show the page.", previous: $e);
        }
        $json = $response->json() ?? [];
        if (($json['ok'] ?? false) !== true) {
            throw new AgentRefused(sprintf('Agent on [%s] refused to show the page: %s (%s)', $this->host, $json['error'] ?? 'unknown_error', $json['hint'] ?? ''), detail: $json);
        }

        return $json['shots'] ?? [];
    }

    public function render(string $url): array
    {
        try {
            $response = Http::timeout(70)->acceptJson()->withToken($this->token)->post($this->baseUrl.'/v1/render', ['url' => $url]);
        } catch (ConnectionException $e) {
            throw new AgentUnreachable("Cannot reach the agent on [{$this->host}] to render a page.", previous: $e);
        }
        $json = $response->json() ?? [];
        if (($json['ok'] ?? false) !== true) {
            throw new AgentRefused(sprintf('Agent on [%s] refused to render: %s (%s)', $this->host, $json['error'] ?? 'unknown_error', $json['hint'] ?? ''), detail: $json);
        }

        return $json['render'] ?? [];
    }

    /** Keep a site out of search engines (agent: X-Robots-Tag at the edge), or not. */
    public function setNoIndex(string $id, bool $noIndex): void
    {
        $this->send('put', "/v1/sites/$id/indexing", ['noIndex' => $noIndex]);
    }

    /** A new free site's first week: web ports only out, no UDP, ~8 Mbit/s (agent restrict.go). */
    public function setRestrictedEgress(string $id, bool $restricted): void
    {
        $this->send('put', "/v1/sites/$id/egress", ['restricted' => $restricted]);
    }

    /** Every site's CPU counter on this host (agent sites/cpu.go): {sites: [...], at}. */
    public function cpu(): array
    {
        return $this->send('get', '/v1/cpu');
    }

    /**
     * A whole-site malware scan (agent sites/scan.go): list of findings, each
     * {path, kind: malware|obfuscated, detail}. Throws if the scan could not
     * run - never an empty "clean" list in its place.
     */
    /**
     * @return array{findings: array, incomplete: ?string} incomplete: why part of
     *                                                     the scan (ClamAV) could not run - the rules' findings still count.
     */
    public function scanSite(string $id): array
    {
        // A whole site streamed through ClamAV: about a minute for a Laravel
        // app with its vendor/, so well past the usual timeout.
        $long = new self($this->host, $this->baseUrl, $this->token, 900);
        $r = $long->send('post', "/v1/sites/$id/scan");

        return ['findings' => $r['findings'] ?? [], 'incomplete' => $r['incomplete'] ?? null];
    }

    public function search(string $id, string $q, int $limit = 200): array
    {
        return $this->send('get', "/v1/sites/$id/search", query: ['q' => $q, 'limit' => $limit])['hits'] ?? [];
    }

    /**
     * grep -r: $o is pattern, regex, icase, word, under, include (a list of
     * name globs) and limit -> ['hits' => [...], 'truncated' => bool].
     */
    public function grep(string $id, array $o): array
    {
        $r = $this->send('get', "/v1/sites/$id/grep?".self::flags($o));

        return ['hits' => $r['hits'] ?? [], 'truncated' => (bool) ($r['truncated'] ?? false)];
    }

    /**
     * find: $o is under, name, icase, type (f|d), newer (Unix seconds),
     * maxdepth, all and limit -> entries, file count and bytes for du.
     */
    public function find(string $id, array $o): array
    {
        $r = $this->send('get', "/v1/sites/$id/find?".self::flags($o));

        return ['entries' => $r['entries'] ?? [], 'files' => (int) ($r['files'] ?? 0), 'bytes' => (int) ($r['bytes'] ?? 0), 'truncated' => (bool) ($r['truncated'] ?? false), 'skipped' => $r['skipped'] ?? []];
    }

    /**
     * git clone: a public GitHub repository into a new folder of the site.
     * The host downloads and scans it, so this waits longer than most calls.
     */
    public function cloneRepository(string $id, string $repository, ?string $ref, ?string $into): array
    {
        try {
            $response = Http::timeout(200)->acceptJson()->withToken($this->token)
                ->post($this->baseUrl."/v1/sites/$id/clone", ['repository' => $repository, 'ref' => $ref ?? '', 'into' => $into ?? '']);
        } catch (ConnectionException $e) {
            throw new AgentUnreachable("Cannot reach the agent on [{$this->host}]. Whether the clone finished is UNKNOWN.", previous: $e);
        }
        $json = $response->json() ?? [];
        if (($json['ok'] ?? false) !== true) {
            throw new AgentRefused(sprintf('Agent on [%s] refused the clone: %s (%s)', $this->host,
                $json['error'] ?? 'unknown_error', $json['hint'] ?? 'no hint given'), detail: $json);
        }

        return ['clone' => $json['clone'] ?? []];
    }

    /**
     * Replace the whole site with a public GitHub repository: checked and
     * scanned now, then backed up and swapped in the background.
     */
    public function cloneReplace(string $id, string $repository, ?string $ref, bool $confirm): array
    {
        try {
            $response = Http::timeout(200)->acceptJson()->withToken($this->token)
                ->post($this->baseUrl."/v1/sites/$id/clone-replace", ['repository' => $repository, 'ref' => $ref ?? '', 'confirm' => $confirm]);
        } catch (ConnectionException $e) {
            throw new AgentUnreachable("Cannot reach the agent on [{$this->host}]. Whether the replace started is UNKNOWN.", previous: $e);
        }
        $json = $response->json() ?? [];
        if (($json['ok'] ?? false) !== true) {
            throw new AgentRefused(sprintf('Agent on [%s] refused the replace: %s (%s)', $this->host,
                $json['error'] ?? 'unknown_error', $json['hint'] ?? 'no hint given'), detail: $json);
        }

        return ['operation' => $json['operation'] ?? null];
    }

    /** The current or last backup, restore or clone-replace. */
    public function operation(string $id): array
    {
        return ['operation' => $this->send('get', "/v1/sites/$id/operation")['operation'] ?? null];
    }

    /** Booleans as 1 (Go reads "1"), unset options left out; a list as repeated keys. */
    private static function flags(array $o): string
    {
        $parts = [];
        foreach ($o as $k => $v) {
            if ($v === null || $v === false || $v === '') {
                continue;
            }
            foreach ((array) $v as $one) {
                $parts[] = rawurlencode($k).'='.rawurlencode($one === true ? '1' : (string) $one);
            }
        }

        return implode('&', $parts);
    }

    /** Raw bytes to a path in the site; streamed, never held whole in memory. */
    public function upload(string $id, string $path, $stream): array
    {
        try {
            $response = Http::timeout(max($this->timeout, 120))->acceptJson()->withToken($this->token)
                ->withBody(Utils::streamFor($stream), 'application/octet-stream')
                ->put($this->baseUrl."/v1/sites/$id/upload?".http_build_query(['path' => $path]));
        } catch (ConnectionException $e) {
            throw new AgentUnreachable("Cannot reach the agent on [{$this->host}]. Whether the upload took effect is UNKNOWN.", previous: $e);
        }
        $json = $response->json() ?? [];
        if (($json['ok'] ?? false) !== true) {
            throw new AgentRefused(sprintf('Agent on [%s] refused the upload: %s (%s)', $this->host,
                $json['error'] ?? 'unknown_error', $json['hint'] ?? 'no hint given'), detail: $json);
        }

        return $json;
    }

    /**
     * A file's bytes as a stream, and its name.
     *
     * @return array{name: string, body: StreamInterface}
     */
    public function download(string $id, string $path): array
    {
        try {
            $response = Http::timeout(max($this->timeout, 120))->withToken($this->token)->withOptions(['stream' => true])
                ->get($this->baseUrl."/v1/sites/$id/download?".http_build_query(['path' => $path]));
        } catch (ConnectionException $e) {
            throw new AgentUnreachable("Cannot reach the agent on [{$this->host}].", previous: $e);
        }
        if (str_contains((string) $response->header('Content-Type'), 'json')) {
            $json = json_decode((string) $response->body(), true) ?? [];
            throw new AgentRefused(sprintf('Agent on [%s] refused the download: %s (%s)', $this->host,
                $json['error'] ?? 'unknown_error', $json['hint'] ?? 'no hint given'), detail: $json);
        }
        preg_match('/filename="([^"]+)"/', (string) $response->header('Content-Disposition'), $m);

        return ['name' => $m[1] ?? 'download', 'body' => $response->toPsrResponse()->getBody()];
    }

    /**
     * The site's whole database as .sql.gz, streamed. With $beforeImport, the
     * copy the last import saved instead.
     *
     * @return array{name: string, body: StreamInterface}
     */
    public function dbExport(string $id, bool $beforeImport = false): array
    {
        try {
            $response = Http::timeout(1900)->withToken($this->token)->withOptions(['stream' => true])
                ->get($this->baseUrl."/v1/sites/$id/db/export".($beforeImport ? '?saved=before-import' : ''));
        } catch (ConnectionException $e) {
            throw new AgentUnreachable("Cannot reach the agent on [{$this->host}].", previous: $e);
        }
        if (str_contains((string) $response->header('Content-Type'), 'json')) {
            $json = json_decode((string) $response->body(), true) ?? [];
            throw new AgentRefused(sprintf('Agent on [%s] refused the export: %s (%s)', $this->host,
                $json['error'] ?? 'unknown_error', $json['hint'] ?? 'no hint given'), detail: $json);
        }
        preg_match('/filename="([^"]+)"/', (string) $response->header('Content-Disposition'), $m);

        return ['name' => $m[1] ?? "$id.sql.gz", 'body' => $response->toPsrResponse()->getBody()];
    }

    /** Loads a .sql or .sql.gz dump; the agent saves the current database first. */
    /**
     * A site's files or version history as a gzipped tar stream, for moving
     * the site to another host (SiteMover). $kind: files | history.
     */
    public function transferExport(string $id, string $kind): StreamInterface
    {
        try {
            $response = Http::timeout(7200)->withToken($this->token)->withOptions(['stream' => true])
                ->get($this->baseUrl."/v1/sites/$id/transfer/$kind");
        } catch (ConnectionException $e) {
            throw new AgentUnreachable("Cannot reach the agent on [{$this->host}].", previous: $e);
        }
        if (! $response->successful() || str_contains((string) $response->header('Content-Type'), 'json')) {
            $json = json_decode((string) $response->body(), true) ?? [];
            throw new AgentRefused(sprintf('Agent on [%s] refused the %s export: %s (%s)', $this->host, $kind,
                $json['error'] ?? 'unknown_error', $json['hint'] ?? 'no hint given'), detail: $json);
        }

        return $response->toPsrResponse()->getBody();
    }

    public function transferImport(string $id, string $kind, $stream): array
    {
        try {
            $response = Http::timeout(7200)->acceptJson()->withToken($this->token)
                ->withBody(Utils::streamFor($stream), 'application/gzip')
                ->put($this->baseUrl."/v1/sites/$id/transfer/$kind");
        } catch (ConnectionException $e) {
            throw new AgentUnreachable("Cannot reach the agent on [{$this->host}]. Whether the import took effect is UNKNOWN.", previous: $e);
        }
        $json = $response->json() ?? [];
        if (($json['ok'] ?? false) !== true) {
            throw new AgentRefused(sprintf('Agent on [%s] refused the %s import: %s (%s)', $this->host, $kind,
                $json['error'] ?? 'unknown_error', $json['hint'] ?? 'no hint given'), detail: $json);
        }

        return $json;
    }

    /** Laravel's maintenance mode on the site, for the minutes a move takes. */
    public function setMaintenance(string $id, bool $down): void
    {
        $this->send('put', "/v1/sites/$id/maintenance", ['down' => $down]);
    }

    public function dbImport(string $id, $stream): array
    {
        try {
            $response = Http::timeout(1900)->acceptJson()->withToken($this->token)
                ->withBody(Utils::streamFor($stream), 'application/octet-stream')
                ->put($this->baseUrl."/v1/sites/$id/db/import?confirm=1");
        } catch (ConnectionException $e) {
            throw new AgentUnreachable("Cannot reach the agent on [{$this->host}]. Whether the import took effect is UNKNOWN.", previous: $e);
        }
        $json = $response->json() ?? [];
        if (($json['ok'] ?? false) !== true) {
            throw new AgentRefused(sprintf('Agent on [%s] refused the import: %s (%s)', $this->host,
                $json['error'] ?? 'unknown_error', $json['hint'] ?? 'no hint given'), detail: $json);
        }

        return $json;
    }

    /**
     * The site database's snapshots, newest first: taken before every import,
     * migration and seeder (agent dbsnapshots.go).
     *
     * @return list<array{name: string, reason: string, at: string, bytes: int}>
     */
    public function dbSnapshots(string $id): array
    {
        return $this->send('get', "/v1/sites/$id/db/snapshots")['snapshots'] ?? [];
    }

    /** Load a snapshot back; what it replaces is snapshotted first. */
    public function dbRestoreSnapshot(string $id, string $name): array
    {
        try {
            $response = Http::timeout(1900)->acceptJson()->withToken($this->token)
                ->post($this->baseUrl."/v1/sites/$id/db/snapshots/".rawurlencode($name).'/restore', ['confirm' => true]);
        } catch (ConnectionException $e) {
            throw new AgentUnreachable("Cannot reach the agent on [{$this->host}]. Whether the restore took effect is UNKNOWN.", previous: $e);
        }
        $json = $response->json() ?? [];
        if (($json['ok'] ?? false) !== true) {
            throw new AgentRefused(sprintf('Agent on [%s] refused the restore: %s (%s)', $this->host,
                $json['error'] ?? 'unknown_error', $json['hint'] ?? 'no hint given'), detail: $json);
        }

        return $json;
    }

    /** @return array{database: string, tables: array} */
    public function dbTables(string $id): array
    {
        $r = $this->send('get', "/v1/sites/$id/db");

        return ['database' => $r['database'] ?? '', 'tables' => $r['tables'] ?? []];
    }

    /**
     * Runs as the site's own MySQL user. A statement that may change data is
     * refused (AgentRefused, detail['error'] = 'needs_write') unless $write.
     */
    public function dbQuery(string $id, string $sql, bool $write = false): array
    {
        return $this->send('post', "/v1/sites/$id/db/query", ['sql' => $sql, 'write' => $write])['result'] ?? [];
    }

    public function reconcile(): array
    {
        return $this->send('post', '/v1/reconcile')['changed'] ?? [];
    }

    /**
     * @throws AgentUnreachable the tunnel or the agent is down - the state of
     *                          the host is UNKNOWN, which is not the same as
     *                          "nothing happened"
     * @throws AgentRefused the agent answered and said no, with a reason
     */
    /**
     * Query parameters and request bodies are kept STRICTLY separate here,
     * because Laravel's HTTP client gives the same second argument three
     * different meanings depending on the verb:
     *
     *   get($url, $array)     - REPLACES the url's query string, even when the
     *                           array is empty
     *   delete($url, $array)  - sends the array as the request BODY, and the
     *                           url's query survives
     *   put($url, $array)     - sends the array as the JSON body
     *
     * Passing `[]` uniformly produced two separate silent failures: every file
     * READ came back as a directory listing because `?read=1&path=...` was
     * wiped off the url, and every file DELETE was refused with `no_path`
     * because the path went into a body the agent does not read. Both survived
     * the live checks, which used curl directly rather than this class.
     *
     * So: $query is always built into the url, $body is only ever sent for the
     * verbs that carry one, and the second argument is never `[]`.
     */
    /**
     * For endpoints whose ok:false still carries a result worth returning -
     * a command that ran and failed. Refusals (4xx) still throw AgentRefused.
     */
    private function sendRaw(string $method, string $path, array $body = []): array
    {
        try {
            $response = Http::timeout(max($this->timeout, 660))->acceptJson()->withToken($this->token)
                ->{$method}($this->baseUrl.$path, $body);
        } catch (ConnectionException $e) {
            throw new AgentUnreachable("Cannot reach the agent on [{$this->host}]. Whether the command ran is UNKNOWN.", previous: $e);
        }
        $json = $response->json() ?? [];
        if (isset($json['result'])) {
            return $json;
        }
        throw new AgentRefused(sprintf('Agent on [%s] refused %s: %s (%s)', $this->host, $path,
            $json['error'] ?? 'unknown_error', $json['hint'] ?? 'no hint given'), detail: $json);
    }

    private function send(string $method, string $path, array $body = [], bool $authenticated = true, array $query = []): array
    {
        $request = Http::timeout($this->timeout)->acceptJson();
        if ($authenticated) {
            $request = $request->withToken($this->token);
        }

        $url = $this->baseUrl.$path;
        if ($query !== []) {
            $url .= '?'.http_build_query($query);
        }

        try {
            $response = match (strtolower($method)) {
                // null, not []: an empty array would replace the query we just built.
                'get' => $request->get($url),
                'delete' => $request->delete($url),
                default => $request->{$method}($url, $body),
            };
        } catch (ConnectionException $e) {
            throw new AgentUnreachable(
                "Cannot reach the agent on [{$this->host}] at {$this->baseUrl}. ".
                "The SSH tunnel is probably down: check `systemctl status cic-tunnel@{$this->host}`. ".
                'Whether the operation took effect on the host is UNKNOWN.',
                previous: $e,
            );
        }

        $json = $response->json() ?? [];

        // The agent's own convention: `ok` is the verdict, not the transport.
        // Trusting the status code alone would read `partially_removed` (HTTP
        // 500, ok:false, but three of five parts actually removed) as a clean
        // failure, and a caller would retry a delete that had half happened.
        if (($json['ok'] ?? false) !== true) {
            throw new AgentRefused(
                sprintf(
                    'Agent on [%s] refused %s %s: %s (%s)',
                    $this->host, strtoupper($method), $path,
                    $json['error'] ?? 'unknown_error',
                    $json['hint'] ?? 'no hint given',
                ),
                detail: $json,
            );
        }

        return $json;
    }
}
