<?php

namespace App\Fleet;

use Illuminate\Http\Client\ConnectionException;
use Illuminate\Support\Facades\Http;
use RuntimeException;

/**
 * Talks to one host's cic-agent.
 *
 * Every method returns what it OBSERVED, and says so. The agent follows the
 * same rule on its side: its `ok` is the verdict, not the transport, and a
 * delete that removed three of four parts reports `partially_removed` with the
 * breakdown rather than success. This class must not flatten that back into a
 * boolean - a site whose container is gone but whose vhost still answers is
 * not "deleted", and reporting it as such is how a domain keeps serving a
 * customer who has left.
 */
class AgentClient
{
    public function __construct(
        public readonly string $host,
        private readonly string $baseUrl,
        private readonly string $token,
        private readonly int $timeout = 120,
    ) {}

    public static function for(string $host): self
    {
        $cfg = config("fleet.hosts.$host");
        if (! $cfg) {
            throw new RuntimeException("Unknown host [$host]. Known hosts: " . implode(', ', array_keys(config('fleet.hosts'))));
        }

        // A host we have explicitly ruled out must fail here, not merely be
        // absent from a list someone could edit.
        if (in_array($cfg['ip'], config('fleet.forbidden_ips'), true)) {
            throw new RuntimeException("Host [$host] resolves to {$cfg['ip']}, which is out of scope for this fleet.");
        }

        // config(), never env(): see config/fleet.php. An env() call here
        // returns null under a cached config, so the agent would be called
        // with an empty bearer token in production and refuse every request.
        $token = config("fleet.tokens.$host");
        if (! $token) {
            throw new RuntimeException(
                "No agent token for [$host]. Set CIC_TOKEN_" . strtoupper($host) . " in .env; " .
                'it is generated by infra/install-agent.sh and lives in /opt/codeinchrome/etc/agent.env on the host.'
            );
        }

        return new self($host, "http://127.0.0.1:{$cfg['tunnel_port']}", $token, config('fleet.timeout'));
    }

    public function health(): array
    {
        return $this->send('get', '/healthz', authenticated: false);
    }

    /** @return array<int, array{id: string, current: bool, image: string}> */
    public function imageStatuses(): array
    {
        return $this->send('get', '/v1/images')['sites'] ?? [];
    }

    /** "recreated" or "current"; throws if the new container does not answer. */
    public function recreate(string $id): string
    {
        return $this->send('post', "/v1/sites/$id/recreate")['outcome'] ?? '';
    }

    public function hostStats(): array
    {
        return $this->send('get', '/v1/host/stats')['stats'] ?? [];
    }

    public function hostInfo(): array
    {
        return $this->send('get', '/v1/host');
    }

    /** @return array<int, array<string, mixed>> */
    public function sites(): array
    {
        return $this->send('get', '/v1/sites')['sites'] ?? [];
    }

    public function site(string $id): array
    {
        return $this->send('get', "/v1/sites/$id")['site'] ?? [];
    }

    public function createSite(string $id, string $domain, string $cpu, string $memory, int $diskGb = 1): array
    {
        return $this->send('post', '/v1/sites', [
            'id' => $id, 'domain' => $domain, 'cpuLimit' => $cpu, 'memLimit' => $memory, 'diskGb' => $diskGb,
        ])['site'] ?? [];
    }

    /**
     * Apply new ceilings to a running site. Returns what the host says it
     * applied, per part: CPU and memory change immediately, and a disk only
     * ever grows - a smaller plan leaves it as it is.
     *
     * @return array<string, string>
     */
    public function setLimits(string $id, string $cpu, string $memory, int $diskGb): array
    {
        return $this->send('put', "/v1/sites/$id/limits", [
            'cpuLimit' => $cpu, 'memLimit' => $memory, 'diskGb' => $diskGb,
        ])['applied'] ?? [];
    }

    /**
     * Run one allow-listed artisan or composer command. A non-zero exit is
     * returned as a result with ok=false, NOT thrown: the output is what the
     * caller needs to see.
     */
    public function runCommand(string $id, string $tool, array $args, bool $confirm = false): array
    {
        return $this->sendRaw('post', "/v1/sites/$id/command", ['tool' => $tool, 'args' => array_values($args), 'confirm' => $confirm]);
    }

    public function logs(string $id, string $source, int $lines = 200): array
    {
        return $this->send('get', "/v1/sites/$id/logs", query: ['source' => $source, 'lines' => $lines])['log'] ?? [];
    }

    /** Replace the site's verified custom domains; the agent rewrites the vhost. */
    public function setAliases(string $id, array $aliases): array
    {
        return $this->send('put', "/v1/sites/$id/aliases", ['aliases' => array_values($aliases)])['site'] ?? [];
    }

    /** @return array<int, array<string, mixed>> one entry per site on the host */
    public function usage(): array
    {
        return $this->send('get', '/v1/usage')['usage'] ?? [];
    }

    /**
     * @return array<string, string> per part: "removed", "absent" or "failed".
     *
     * Three states rather than a boolean, because `docker rm -f` exits 0 for a
     * container that never existed - so a delete aimed at the wrong host used
     * to report success for work it had not done.
     */
    public function deleteSite(string $id): array
    {
        return $this->send('delete', "/v1/sites/$id")['parts'] ?? [];
    }

    /** @return array{path: string, entries: array, truncated: bool} */
    public function listFiles(string $id, string $path = '/'): array
    {
        return $this->send('get', "/v1/sites/$id/files", query: ['path' => $path])['listing'] ?? [];
    }

    public function readFile(string $id, string $path): string
    {
        return $this->readFileWithRevision($id, $path)['content'];
    }

    /** @return array{content: string, revision: string} */
    public function readFileWithRevision(string $id, string $path): array
    {
        $r = $this->send('get', "/v1/sites/$id/files", query: ['read' => 1, 'path' => $path]);

        return ['content' => $r['content'] ?? '', 'revision' => $r['revision'] ?? ''];
    }

    /**
     * @param  string  $expect  "" to write unconditionally, "absent" to create
     *                          only if missing, or the revision from a read.
     *                          A mismatch is an AgentRefused whose
     *                          detail['error'] is "conflict", and NOTHING was
     *                          written.
     */
    public function writeFile(string $id, string $path, string $content, string $expect = ''): array
    {
        return $this->send('put', "/v1/sites/$id/files", ['path' => $path, 'content' => $content, 'expect' => $expect]);
    }

    public function deleteFile(string $id, string $path): bool
    {
        return (bool) ($this->send('delete', "/v1/sites/$id/files", query: ['path' => $path])['deleted'] ?? false);
    }

    /** @return array{database: string, tables: array} */
    public function dbTables(string $id): array
    {
        $r = $this->send('get', "/v1/sites/$id/db");

        return ['database' => $r['database'] ?? '', 'tables' => $r['tables'] ?? []];
    }

    /**
     * Runs as the site's own MySQL user. A statement that may change data is
     * refused (AgentRefused, detail['error'] = 'needs_write') unless $write.
     */
    public function dbQuery(string $id, string $sql, bool $write = false): array
    {
        return $this->send('post', "/v1/sites/$id/db/query", ['sql' => $sql, 'write' => $write])['result'] ?? [];
    }

    public function reconcile(): array
    {
        return $this->send('post', '/v1/reconcile')['changed'] ?? [];
    }

    /**
     * @throws AgentUnreachable  the tunnel or the agent is down - the state of
     *                           the host is UNKNOWN, which is not the same as
     *                           "nothing happened"
     * @throws AgentRefused      the agent answered and said no, with a reason
     */
    /**
     * Query parameters and request bodies are kept STRICTLY separate here,
     * because Laravel's HTTP client gives the same second argument three
     * different meanings depending on the verb:
     *
     *   get($url, $array)     - REPLACES the url's query string, even when the
     *                           array is empty
     *   delete($url, $array)  - sends the array as the request BODY, and the
     *                           url's query survives
     *   put($url, $array)     - sends the array as the JSON body
     *
     * Passing `[]` uniformly produced two separate silent failures: every file
     * READ came back as a directory listing because `?read=1&path=...` was
     * wiped off the url, and every file DELETE was refused with `no_path`
     * because the path went into a body the agent does not read. Both survived
     * the live checks, which used curl directly rather than this class.
     *
     * So: $query is always built into the url, $body is only ever sent for the
     * verbs that carry one, and the second argument is never `[]`.
     */
    /**
     * For endpoints whose ok:false still carries a result worth returning -
     * a command that ran and failed. Refusals (4xx) still throw AgentRefused.
     */
    private function sendRaw(string $method, string $path, array $body = []): array
    {
        try {
            $response = Http::timeout(max($this->timeout, 660))->acceptJson()->withToken($this->token)
                ->{$method}($this->baseUrl . $path, $body);
        } catch (ConnectionException $e) {
            throw new AgentUnreachable("Cannot reach the agent on [{$this->host}]. Whether the command ran is UNKNOWN.", previous: $e);
        }
        $json = $response->json() ?? [];
        if (isset($json['result'])) {
            return $json;
        }
        throw new AgentRefused(sprintf('Agent on [%s] refused %s: %s (%s)', $this->host, $path,
            $json['error'] ?? 'unknown_error', $json['hint'] ?? 'no hint given'), detail: $json);
    }

    private function send(string $method, string $path, array $body = [], bool $authenticated = true, array $query = []): array
    {
        $request = Http::timeout($this->timeout)->acceptJson();
        if ($authenticated) {
            $request = $request->withToken($this->token);
        }

        $url = $this->baseUrl . $path;
        if ($query !== []) {
            $url .= '?' . http_build_query($query);
        }

        try {
            $response = match (strtolower($method)) {
                // null, not []: an empty array would replace the query we just built.
                'get' => $request->get($url),
                'delete' => $request->delete($url),
                default => $request->{$method}($url, $body),
            };
        } catch (ConnectionException $e) {
            throw new AgentUnreachable(
                "Cannot reach the agent on [{$this->host}] at {$this->baseUrl}. " .
                "The SSH tunnel is probably down: check `systemctl status cic-tunnel@{$this->host}`. " .
                "Whether the operation took effect on the host is UNKNOWN.",
                previous: $e,
            );
        }

        $json = $response->json() ?? [];

        // The agent's own convention: `ok` is the verdict, not the transport.
        // Trusting the status code alone would read `partially_removed` (HTTP
        // 500, ok:false, but three of five parts actually removed) as a clean
        // failure, and a caller would retry a delete that had half happened.
        if (($json['ok'] ?? false) !== true) {
            throw new AgentRefused(
                sprintf(
                    'Agent on [%s] refused %s %s: %s (%s)',
                    $this->host, strtoupper($method), $path,
                    $json['error'] ?? 'unknown_error',
                    $json['hint'] ?? 'no hint given',
                ),
                detail: $json,
            );
        }

        return $json;
    }
}
