<?php

return [
    /*
     * How the control plane reaches each host agent.
     *
     * The agent binds 127.0.0.1:9440 and nothing else, so it cannot be reached
     * across the internet at all. That is deliberate: it is the component that
     * can create and destroy every customer site on a host, and an open port
     * with a bearer token is one token leak away from total compromise.
     *
     * A persistent SSH tunnel per host maps a local port to the agent's
     * loopback port, so this application speaks plain HTTP to 127.0.0.1 and
     * the traffic crosses the internet inside SSH. Chosen over the
     * alternatives because it adds NO new listening port on a customer host,
     * no new daemon, and no new key material: it reuses the hardened,
     * keys-only SSH that already exists and that we already depend on for
     * deployment. WireGuard would also work and is faster, but it is another
     * daemon and another set of keys to rotate for traffic that amounts to a
     * few control calls a minute.
     *
     * See infra/tunnels.sh for the systemd units that hold the tunnels open.
     */
    /*
     * Customer hosts ONLY.
     *
     * h2 is deliberately absent: it runs this control plane, which holds every
     * host's agent token and the Cloudflare API key. Those are the keys to the
     * entire fleet, and they have no business sitting on a machine that also
     * runs customer containers. Container isolation here is real and tested
     * (infra/verify-isolation.sh), but a single escape should not also be a
     * total compromise, and separating the two costs one machine.
     */
    /*
     * The hosts come from ONE registry, infra/hosts.env (CIC_HOSTS="h1:ip h3:ip
     * ..."), never from a list in code: adding a server is infra/add-host.sh,
     * which registers it there and redeploys, and nothing here changes.
     * deploy-control.sh writes CIC_HOSTS into the control plane's .env; in
     * development the registry file itself is read. A host named hN is
     * reached through its tunnel on 127.0.0.1:(9440+N) (infra/tunnels.sh).
     *
     * CIC_HOST_STATES marks hosts that take no NEW sites ("h3:draining") while
     * their existing sites keep running - the first step of retiring one.
     */
    'hosts' => (function () {
        $registry = env('CIC_HOSTS');
        if ($registry === null) {
            // The addresses are in hosts.local.env (never committed), beside hosts.env.
            foreach ([base_path('hosts.local.env'), base_path('../infra/hosts.local.env')] as $file) {
                if (is_readable($file) && preg_match('/^CIC_HOSTS="([^"]+)"/m', (string) file_get_contents($file), $m)) {
                    $registry = $m[1];
                    break;
                }
            }
        }
        $states = [];
        foreach (preg_split('/\s+/', trim((string) env('CIC_HOST_STATES', '')), -1, PREG_SPLIT_NO_EMPTY) as $entry) {
            [$name, $state] = array_pad(explode(':', $entry, 2), 2, 'active');
            $states[$name] = $state;
        }
        $hosts = [];
        foreach (preg_split('/\s+/', trim((string) $registry), -1, PREG_SPLIT_NO_EMPTY) as $entry) {
            [$name, $ip] = array_pad(explode(':', $entry, 2), 2, '');
            if (! preg_match('/^h(\d+)$/', $name, $n) || ! filter_var($ip, FILTER_VALIDATE_IP)) {
                continue; // a malformed entry is left out, never guessed at
            }
            $hosts[$name] = [
                'ip' => $ip,
                'tunnel_port' => 9440 + (int) $n[1],
                'capacity' => (int) env('CIC_HOST_CAPACITY', 60),
                'state' => $states[$name] ?? 'active',
            ];
        }

        return $hosts;
    })(),

    /*
     * Per-host bearer tokens. Resolved HERE, in a config file, and never with
     * env() from application code: `php artisan config:cache` - which every
     * production deploy runs - makes env() return null everywhere outside
     * config files. Read from application code it would work perfectly in
     * development and authenticate against nothing in production.
     *
     * Generated by infra/install-agent.sh; each lives in
     * /opt/codeinchrome/etc/agent.env on its host.
     */
    'tokens' => (function () {
        $tokens = [];
        foreach ($_ENV + $_SERVER as $key => $value) {
            if (is_string($key) && preg_match('/^CIC_TOKEN_(H\d+)$/', $key, $m) && is_string($value) && $value !== '') {
                $tokens[strtolower($m[1])] = $value;
            }
        }

        return $tokens;
    })(),

    'cloudflare' => [
        'token' => env('CLOUDFLARE_API_TOKEN'),
        'zone_id' => env('CLOUDFLARE_ZONE_ID'),
        'zone_name' => env('CLOUDFLARE_ZONE_NAME', 'codeinchrome.com'),
    ],

    'timeout' => 120,

    /*
     * The oldest agent a site may be provisioned onto.
     *
     * A mixed-version fleet does not fail loudly, it produces DIFFERENT SITES:
     * during this build, h1 ran 0.2.0 (which seeds a Laravel skeleton and
     * generates a per-site application key) while h2 still ran 0.1.0 (which
     * does neither). A provision routed to h2 reported success and created an
     * empty site with no application key. Reads and status calls are fine
     * against any version; creating is not.
     */
    /*
     * Where monitoring alerts are POSTed as {"text": "..."} - a Slack incoming
     * webhook, or Discord's /slack endpoint. Unset means alerts go only to the
     * log and the operator status page, which is recorded on each incident.
     */
    'alert_webhook' => env('CIC_ALERT_WEBHOOK'),

    /*
     * Accounts that can see the operator status page. By address, from the
     * environment, so no one can make themselves an operator from inside the
     * application.
     */
    'admin_emails' => array_filter(array_map('trim', explode(',', (string) env('CIC_ADMIN_EMAILS', '')))),

    /*
     * Whether mail actually leaves the building. Password reset and email
     * verification are offered ONLY when it does: a "forgot password" link
     * whose email is written to a log file is worse than no link.
     */
    'mail_enabled' => ! in_array(env('MAIL_MAILER', 'log'), ['log', 'array'], true),

    /*
     * What the fleet can sell (App\Fleet\Stock). Capacity is each host's own
     * reported resources minus the reserve, times the overcommit. Sites rarely
     * sit at their memory ceiling and CPU is shared by design; a site's disk
     * is a kernel-enforced ceiling on a sparse image, so it is overcommitted
     * too, and watched (the host disk alert).
     */
    'stock' => [
        'overcommit' => [
            'cpu' => (float) env('CIC_OVERCOMMIT_CPU', 8.0),
            'memory' => (float) env('CIC_OVERCOMMIT_MEMORY', 1.5),
            // Per-site disks are sparse images: a quota is a ceiling, not space
            // taken. Measured 2026-09-24: sites use 0.6-0.8 GB of theirs and
            // the hosts' disks were 6-7% full. 2.5x keeps a full fleet of
            // Starters (5 GB per site) memory-bound; the host disk alert
            // (Monitoring::DISK_FREE_MIN) fires at 25% free, in time to move sites.
            'disk' => (float) env('CIC_OVERCOMMIT_DISK', 2.5),
        ],
        // For each host's own services: MySQL, Caddy, the agent, the OS.
        // memory: the host's own services, plus clamd (~1 GB measured on
        // 2026-09-25, holding the malware signatures in memory).
        'reserve' => ['memory_mb' => 3072, 'disk_gb' => 15],
        // Figures older than this (the monitor refreshes them every minute)
        // add no capacity: we do not sell into a fleet we cannot see.
        'fresh_seconds' => 600,
        // Below this many of a paid plan left, the operator is alerted (Monitoring).
        'alert_below' => (int) env('CIC_STOCK_ALERT_BELOW', 3),
    ],

    'min_agent_version' => '0.26.8',

    // Touched by the control plane's backup after each complete run
    // (infra/setup-control-backup.sh); Monitoring alerts when it is older
    // than a day and a bit. Unset (development): not checked.
    'control_backup_stamp' => env('CIC_CONTROL_BACKUP_STAMP'),

    // Told of every new site and domain (App\Fleet\OwnerNotifier). Unset: no mail.
    'owner_notify_email' => env('CIC_OWNER_NOTIFY_EMAIL'),

    /*
     * The zone every free subdomain is created under, and addresses that are
     * off limits: servers outside this fleet that must never be provisioned
     * onto. Kept out of the repository (infra/hosts.local.env), written into
     * the control plane's .env as CIC_FORBIDDEN_HOSTS by deploy-control.sh.
     */
    'zone' => env('CIC_ZONE', 'codeinchrome.com'),
    'forbidden_ips' => preg_split('/\s+/', trim((string) env('CIC_FORBIDDEN_HOSTS', '')), -1, PREG_SPLIT_NO_EMPTY),
];
