<?php

return [
    /*
     * How the control plane reaches each host agent.
     *
     * The agent binds 127.0.0.1:9440 and nothing else, so it cannot be reached
     * across the internet at all. That is deliberate: it is the component that
     * can create and destroy every customer site on a host, and an open port
     * with a bearer token is one token leak away from total compromise.
     *
     * A persistent SSH tunnel per host maps a local port to the agent's
     * loopback port, so this application speaks plain HTTP to 127.0.0.1 and
     * the traffic crosses the internet inside SSH. Chosen over the
     * alternatives because it adds NO new listening port on a customer host,
     * no new daemon, and no new key material: it reuses the hardened,
     * keys-only SSH that already exists and that we already depend on for
     * deployment. WireGuard would also work and is faster, but it is another
     * daemon and another set of keys to rotate for traffic that amounts to a
     * few control calls a minute.
     *
     * See infra/tunnels.sh for the systemd units that hold the tunnels open.
     */
    'hosts' => [
        'h1' => ['ip' => '203.0.113.105',   'tunnel_port' => 9441, 'capacity' => 60],
        'h2' => ['ip' => '203.0.113.104',  'tunnel_port' => 9442, 'capacity' => 30],
        'h3' => ['ip' => '203.0.113.102',  'tunnel_port' => 9443, 'capacity' => 60],
        'h4' => ['ip' => '203.0.113.103',  'tunnel_port' => 9444, 'capacity' => 60],
    ],

    /*
     * Per-host bearer tokens. Resolved HERE, in a config file, and never with
     * env() from application code: `php artisan config:cache` - which every
     * production deploy runs - makes env() return null everywhere outside
     * config files. Read from application code it would work perfectly in
     * development and authenticate against nothing in production.
     *
     * Generated by infra/install-agent.sh; each lives in
     * /opt/codeinchrome/etc/agent.env on its host.
     */
    'tokens' => [
        'h1' => env('CIC_TOKEN_H1'),
        'h2' => env('CIC_TOKEN_H2'),
        'h3' => env('CIC_TOKEN_H3'),
        'h4' => env('CIC_TOKEN_H4'),
    ],

    'cloudflare' => [
        'token' => env('CLOUDFLARE_API_TOKEN'),
        'zone_id' => env('CLOUDFLARE_ZONE_ID'),
        'zone_name' => env('CLOUDFLARE_ZONE_NAME', 'codeinchrome.com'),
    ],

    'timeout' => 120,

    /*
     * The oldest agent a site may be provisioned onto.
     *
     * A mixed-version fleet does not fail loudly, it produces DIFFERENT SITES:
     * during this build, h1 ran 0.2.0 (which seeds a Laravel skeleton and
     * generates a per-site application key) while h2 still ran 0.1.0 (which
     * does neither). A provision routed to h2 reported success and created an
     * empty site with no application key. Reads and status calls are fine
     * against any version; creating is not.
     */
    'min_agent_version' => '0.3.0',

    /*
     * The zone every free subdomain is created under, and the hosts that are
     * off limits. 192.0.2.1 is a production mail server with live
     * sites of another business on it and is not part of this fleet.
     */
    'zone' => env('CIC_ZONE', 'codeinchrome.com'),
    'forbidden_ips' => ['192.0.2.1'],
];
